<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Connect4.App\Connect4.App.csproj" />
    <ProjectReference Include="..\Connect4.Engine\Connect4.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\Images\2026 Claus Pedersen.jpg" Link="Images\ClausPedersen.jpg" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Connect4.App.Tests" />
  </ItemGroup>

</Project>
