<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Connect4.Engine.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Book\OpeningBook.txt" LogicalName="Connect4.Engine.Book.OpeningBook.txt" />
  </ItemGroup>

</Project>
